[package]
name = "trekname"
version = "0.1.0"
edition = "2024"
description = "A library containing Star Trek character names and descriptions"
license = "MIT"

[dependencies]
phf = { version = "0.11.3", features = ["macros"] }

[dev-dependencies]
criterion = "0.5.1"
